POST http://localhost:3000/usersCreate
Content-Type: application/json

{
  "name": "zhaotian",
  "matrixNo": "B024230093",
  "password": "holy mama"
}


###
GET http://localhost:3000/usersGet


###
PATCH http://localhost:3000/usersUpdate
Content-Type: application/json


{
    "matrixNo": "B024230093",
    "name": "zhaotian",
    "password": "yabe"
}


###
DELETE http://localhost:3000/usersDelete
Content-Type: application/json

{
  "matrixNo": "B024230093"
}