POST http://localhost:3000/usersCreate
Content-Type: application/json

{
  "name": "maophin",
  "matrixNo": "B02423001",
  "password": "cccc"
}


###
GET http://localhost:3000/usersGet



###
GET http://localhost:3000/users/:id



###
PATCH http://localhost:3000/usersUpdate
Content-Type: application/json


{
    "matrixNo": "B02423001",
    "name": "phinphin",
    "password": "omg"
}
