POST http://localhost:3000/usersCreate
Content-Type: application/json

{
  "name": "zhaotian",
  "matrixNo": "B024230093",
  "password": "asdasd"
}


###
GET http://localhost:3000/usersGet


###
PATCH http://localhost:3000/usersUpdate
Content-Type: application/json


{
    "matrixNo": "B02423001",
    "name": "maophin",
    "password": "noProblem"
}


###
DELETE http://localhost:3000/usersDelete
Content-Type: application/json

{
  "matrixNo": "B024230093"
}


###
PATCH http://localhost:3000/encryptUpdate
Content-Type: application/json


{
    "name": "maophin7",
    "matrixNo": "B02423443",
    "password": "eeee"
}